#!/usr/bin/env node
/* build.cjs — writes wordband-data.js: every word of the served library with its band (the 4.5 brief, P1.1).

   The band of a word is NEVER typed: this script runs tools/wordband/formula.cjs (read its header for the
   formula and every input) over the served corpus exactly as the page loads it (tools/feed-corpus.cjs: both
   word shards, the sentence file, words-patch's QC pass) and writes the result. Change the corpus, a grade
   list or the formula → run this again → tests/word-band.cjs (which recomputes every band and fails on any
   word the shipped file disagrees with).

   THE FILE. window.SB_WORDBAND = { v, n, counts, atlas, b: { 1: 'w|w|…', 2: '…', 3: '…' } } — the words of bands
   1–3, sorted, joined by '|'. Band 4 is not listed: a word with no entry reads as band 4 (wordband.js), the
   careful default that also covers every word the served library does not hold. `atlas` is each Word Atlas
   region's band floor, cut from grade-map.json (formula.cjs atlasFloors). `v` is a hash of the lists,
   so a test can tell a stale file from a fresh one. It is a LAZY file (boot-lazy `wordband`, in every game's
   group and the feed's) — never on the first screen.

   Run: node tools/wordband/build.cjs        (then node tests/word-band.cjs) */
'use strict';
const fs = require('fs'), path = require('path');
const APP = path.resolve(__dirname, '..', '..');
const F = require('./formula.cjs');
const { load } = require('../feed-corpus.cjs');

/* every band, for every headword the served library holds (lower-cased; the first record of a word decides) */
function compute(app) {
  const C = load();
  const ctx = F.context(app || APP, C.DATA);
  const out = new Map();
  for (const r of C.DATA) { if (!r || !r.w) continue; const k = String(r.w).toLowerCase(); if (!out.has(k)) out.set(k, F.score(r, ctx)); }
  return { C, ctx, out };
}
function fnv(s) { let h = 0x811c9dc5; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; } return h.toString(16); }
function encode(out, app) {
  const b = { 1: [], 2: [], 3: [] }, counts = { 1: 0, 2: 0, 3: 0, 4: 0 };
  out.forEach((s, w) => { counts[s.band]++; if (s.band < 4) b[s.band].push(w); });
  const lists = {}; for (const k of [1, 2, 3]) lists[k] = b[k].sort().join('|');
  /* a word holding the separator would split into two; the library holds none, and this says so if one arrives */
  out.forEach((s, w) => { if (w.indexOf('|') >= 0) throw new Error('wordband: a headword holds "|": ' + w); });
  const atlas = F.atlasFloors(app || APP);
  return { v: module.exports.stamp(lists, atlas), n: out.size, counts, atlas, b: lists };
}

if (require.main === module) {
  const { out } = compute(APP);
  const D = encode(out, APP);
  const head = '/* GENERATED by tools/wordband/build.cjs — never edit by hand. THE WORD BANDS (the 4.5 brief, P1.1): every word of the\n'
    + '   served library in band 1 (ages 8–9), 2 (10–11) or 3 (12–13); a word not listed is band 4 (14–15). The formula and its\n'
    + '   inputs — the library\'s rarity band y, length, affixes and the sourced grade lists in grade-map/ — are written out in\n'
    + '   tools/wordband/formula.cjs. ' + D.n + ' words: band 1 ' + D.counts[1] + ' · band 2 ' + D.counts[2]
    + ' · band 3 ' + D.counts[3] + ' · band 4 ' + D.counts[4] + '.\n   Lazy (boot-lazy `wordband`); read only through wordband.js (SB_BAND). */\n';
  fs.writeFileSync(path.join(APP, 'wordband-data.js'), head + 'window.SB_WORDBAND = ' + JSON.stringify(D) + ';\n');
  const sz = fs.statSync(path.join(APP, 'wordband-data.js')).size;
  console.log('wordband-data.js: ' + D.n + ' words — band 1 ' + D.counts[1] + ' · 2 ' + D.counts[2] + ' · 3 ' + D.counts[3] + ' · 4 ' + D.counts[4]
    + ' — ' + (sz / 1024).toFixed(0) + ' KB, v ' + D.v);
}
module.exports = { compute, encode, fnv, stamp: (b, atlas) => fnv(b[1] + '#' + b[2] + '#' + b[3] + '#' + JSON.stringify(atlas)) };
