# Four registers for every campaign in the platform.
# Order: Deadpan, Dry, Absurd, Dark.
TONES = {
# ---------- SHORTLIST PLATES ----------
"P01":["Seventy thousand dollars of outdoor kitchen. Heated by an eighty-nine dollar mushroom.",
       "The kitchen was designed by an architect. The heating was decided in aisle twelve.",
       "They own a pizza oven, a wine fridge and a built-in griddle. They are standing in a circle around a lamp.",
       "Somewhere in this photograph is a man who spent his bonus on this."],
"P02":["Four times a year.",
       "Nine thousand dollars. Roughly two thousand two hundred a pizza.",
       "He has built a brick monument to a food he eats indoors.",
       "He fires it up so he has a reason to stand outside alone."],
"P03":["The Wilsons solved their outdoor heating problem. It cost four hundred thousand dollars.",
       "There is a cheaper way to spend five months somewhere warm.",
       "They drive eleven hundred miles a year to sit outside. They own an outside.",
       "They bought a second house rather than have the conversation."],
"P04":["The outdoor TV cost six thousand dollars. Everyone is watching the small one.",
       "Twenty-two people. One bathroom. An empty terrace nine feet away.",
       "There is an eighty-five inch television outside, broadcasting to four garden chairs and a moth.",
       "The outdoor television has never seen a human face."],
"P05":["Built for the view. Emptied by the breeze.",
       "The architect solved the light, the sightlines and the wind. Two out of three.",
       "Every evening at five past five, the ocean asks everyone to leave.",
       "They paid for the view. They watch it through glass, like everyone else."],
"P06":["Specify the season. Not just the space.",
       "The render never has weather in it.",
       "The render has eleven people in it. November has none.",
       "The client will remember who drew it."],
# ---------- CONCEPT BANK ----------
"B1":["Seventy thousand dollars of outdoor kitchen. Heated by an eighty-nine dollar mushroom.",
      "The kitchen was designed by an architect. The heating was decided in aisle twelve.",
      "They own a pizza oven, a wine fridge and a built-in griddle. They are standing in a circle around a lamp.",
      "Somewhere in this photograph is a man who spent his bonus on this."],
"B2":["Four times a year.",
      "Nine thousand dollars. Roughly two thousand two hundred a pizza.",
      "He has built a brick monument to a food he eats indoors.",
      "He fires it up so he has a reason to stand outside alone."],
"B3":["They solved their outdoor heating problem. It cost four hundred thousand dollars.",
      "There is a cheaper way to spend five months somewhere warm.",
      "They drive eleven hundred miles a year to sit outside. They own an outside.",
      "They bought a second house rather than have the conversation."],
"B4":["“Alfresco. Big tick.” … “Can we go back inside?”",
      "Full marks for the alfresco. Four seconds spent in it.",
      "The judges scored it a nine. From the kitchen.",
      "They filmed the reveal in March. Nobody has been out there since."],
"B5":["Built for the view. Emptied by the breeze.",
      "The architect solved the light, the sightlines and the wind. Two out of three.",
      "Every evening at five past five, the ocean asks everyone to leave.",
      "They paid for the view. They watch it through glass, like everyone else."],
"B6":["The outdoor sofa cost eleven thousand dollars. Everyone is sitting on a log.",
      "Six people, rotating. Like something on a spit.",
      "Every ninety seconds the entire party turns around in perfect silence.",
      "One side of you is always cold. You just take turns choosing which."],
"B7":["Erected in memory of the outdoor season.",
      "Every house has one. Nobody has ever said what it means.",
      "A wicker basket containing the collected surrender of an entire family.",
      "You didn’t buy a basket. You accepted terms."],
"B8":["“Still on for tonight?” · “Yes! Though it’s meant to drop to nine.” · “…indoors?” · “Indoors 👍”",
      "Four messages. The same four messages, since March.",
      "The terrace has its own group chat. It has never been invited.",
      "Nobody suggests outside any more. They stopped a while ago."],
"B9":["“Seamless indoor-outdoor living.”",
      "Photographed in use. Sold on a promise. Used in March.",
      "The prosecco in the listing photo has been there since 2023.",
      "The photograph is the only time anyone sat there."],
"B10":["“It’s actually really nice out here.” / “She’ll be right.”",
       "He is the only guest at his own party.",
       "He has been out there for forty minutes. He will not be broken.",
       "He isn’t enjoying it. He’s proving something."],
"B11":["Melbourne.",
       "Four seasons. One dinner.",
       "By dessert they had removed and replaced every item of clothing they own.",
       "They stopped commenting on it years ago."],
"B12":["Alfresco (n.) — Italian: “in the open air.” Australian: “the bit near the barbecue nobody uses after May.”",
       "An Italian word for an Australian room nobody enters.",
       "Alfresco: a large outdoor space for storing a barbecue you are not using.",
       "It was in the brochure. It’s in the photos. It’s not in the year."],
"B13":["The Petersons observe the end of summer. It is seventy-eight degrees.",
       "The pool closes by calendar, not by weather.",
       "They have folded the umbrellas in perfect silence. One of them is crying.",
       "Nothing has ended. They’ve just decided it has."],
"B14":["The outdoor TV cost six thousand dollars. Everyone is watching the small one.",
       "Twenty-two people. One bathroom. An empty terrace nine feet away.",
       "There is an eighty-five inch television outside, broadcasting to four garden chairs and a moth.",
       "The outdoor television has never seen a human face."],
"B15":["You should not need equipment to attend a dinner party.",
       "Black tie. Thermal base layer.",
       "Twenty adults in ski jackets holding champagne in an award-winning garden. Nobody mentions it.",
       "Everyone is having a lovely time and everyone is lying."],
"B16":["“And how are you finding the terrace?”",
       "The pause is the answer.",
       "The silence lasted long enough that the crew stopped filming.",
       "It’s the best thing they built and the least thing they use."],
"B17":["Specify the season. Not just the space.",
       "The render never has weather in it.",
       "The render has eleven people in it. November has none.",
       "The client will remember who drew it."],
"B18":["Your terrace has an opening time and a closing time. You never agreed to either.",
       "Four o’clock: twelve people. Seven o’clock: one abandoned drink.",
       "The terrace is open from four until six. It sets its own hours.",
       "Nobody decides to go in. They just find themselves inside."],
"B19":["There is a better solution.",
       "The overflow seating is outside. It is November.",
       "Four children eating Thanksgiving dinner in coats, maintaining eye contact through the glass.",
       "They will remember this one."],
"B20":["Beautifully maintained. Entirely unused.",
       "He oils it twice a year. He sits on it twice a year. Never the same day.",
       "The deck has a skincare routine.",
       "He isn’t maintaining it. He’s visiting it."],
# ---------- TRADE + COMMERCIAL ----------
"TB1":["The last item on every punch list is the one you didn’t quote for.",
       "Everything on the list was fixable. The last one wasn’t on the list.",
       "He has signed off forty-one items. The forty-second is a season.",
       "The build is finished. The conversation isn’t."],
"TB2":["“Who built yours?” … “We love it. We’re inside a lot.”",
       "It wasn’t a complaint. It was worse — it was a hesitation.",
       "Three seconds of silence over a fence just cost him his next job.",
       "He’ll never know which job he lost, or why."],
"TB3":["Rough it in now. Or cut it open later.",
       "Four hundred dollars at framing. Six thousand after handover.",
       "They are cutting a hole in a ceiling that took four days to line.",
       "Everyone in this room knows exactly whose fault it is."],
"TB4":["“Can we get one with people in it?”",
       "Every shot in the portfolio is empty. Nobody has asked why.",
       "He has forty photographs of this house and no evidence anyone lives there.",
       "The best work he’s ever done, and he can’t show it in use."],
"TB5":["You sold them 4,200 square feet. You built them 4,800 — for five months a year.",
       "Six hundred square feet, seasonally available.",
       "The most expensive room in the house has no walls and no year.",
       "He charged for it, built it, and handed over something they can’t use."],
"TC1":["Forty covers. Closed for the season.",
       "The waiting list is inside. The empty seats are outside.",
       "There are twenty people queuing nine feet from forty empty chairs.",
       "He turns people away every night while looking at the seats."],
"TC2":["Your terrace is writing your reviews.",
       "Beautiful food. Two stars. The kitchen did nothing wrong.",
       "A chef’s twenty-year career, reviewed by the weather.",
       "It’ll be the first thing anyone reads about him for a year."],
"TC3":["Your booking calendar should not have a meteorologist.",
       "Sixty covers, confirmed and paid. Cancelled at four o’clock by a forecast.",
       "The most powerful person in this venue is a weather app.",
       "She makes the call every time, and every time it costs her the same."],
"TC4":["Ten years of solving it. Ten thousand dollars of not solving it.",
       "Fifteen heaters. Not one worked well enough to stop them buying the next.",
       "A storeroom containing a decade of decisions, all of them the same decision.",
       "Every one of these was going to be the one that fixed it."],
"TC5":["Four hours a week. Moving gas bottles.",
       "Two hundred hours a year of trained hospitality staff, moving cylinders.",
       "She has wheeled the same two bottles across the same courtyard four hundred times.",
       "It’s in nobody’s job description and it’s somebody’s whole shift."],
# ---------- RECEIPTS (punch label) ----------
"R-The Backyard":["Being able to sit in any of it in October",
                  "The cheapest line on the list",
                  "The line item the other five depend on",
                  "The one nobody costed"],
"R-The Rough-In":["Roughing it in at framing, before any of it exists",
                  "The same job, done six months earlier",
                  "Four hundred dollars, spent before there is a ceiling to ruin",
                  "What it would have cost to avoid all of this"],
"R-The Covers":["Making May sellable",
                "Turning May into February",
                "Buying back a month of trading",
                "What the empty seats were worth all along"],
"R-Buying It Twice":["Solving it once",
                     "The version you only buy once",
                     "Ending the collection",
                     "What it would have cost in year one"],
# ---------- PRICED SCENES (punch label) ----------
"S-yard":["Being able to use any of it in October",
          "The cheapest thing in the photograph",
          "The line item the other six depend on",
          "The one nobody costed"],
"S-terrace":["Making those forty covers sellable in May",
             "Turning May into February",
             "Buying back a month of trading",
             "What the rope has been costing all along"],
"S-covers":["Forty seats, sellable in May",
            "Turning May into February, seat by seat",
            "Buying back four hundred covers a month",
            "What every empty chair has been costing"],
"S-graveyard":["Solving it once",
               "The version you only buy once",
               "Ending the collection",
               "What it would have cost in year one"],
}
