/* SB_AVATAR_PNG — which avatars have painted PNG art in avatars/<id>.png.
   Generated by voice/pipeline/avatar-manifest.js after an art batch; SB_AVATAR
   (avatars.js) renders the image instead of the SVG for every id listed here,
   and falls back to the vector art for anything missing. Keep append-only in
   spirit: removing an id silently reverts that character to its SVG. */
window.SB_AVATAR_PNG = {};
