/* SB_AVATAR_PNG — which avatars have painted PNG art in avatars/<id>.png.
   Generated by voice/pipeline/avatar-manifest.js after an art batch; SB_AVATAR
   (avatars.js) renders the image instead of the SVG for every id listed here,
   and falls back to the vector art for anything missing. Keep append-only in
   spirit: removing an id silently reverts that character to its SVG. */
window.SB_AVATAR_PNG = {"bizzy":1,"blossom":1,"bumble":1,"clover":1,"drone":1,"ganesha":1,"honeypot":1,"jester":1,"maestro":1,"mic":1,"nectar":1,"propolis":1,"queenhive":1,"star":1,"waggle":1};
